### PR TITLE
Create maintainance-event.md

### PR DESCRIPTION
**Pull request by adamus1red**
Adds a template type to allow easier creation of scheduled maintainance tasks

### CODE REVIEW

**Comment by adamus1red** [comment]
\cc @AnandChowdhary

**Comment by modem7** [comment]
May I suggest adding the following to help people fill in the template?

https://github.com/upptime/upptime/discussions/444

Specifically: https://rextester.com/WXSMSA7692

**Comment by adamus1red** [comment]
> @adamus1red May I suggest adding the following to help people fill in the template?
> 
> #444
> 
> Specifically: https://rextester.com/UBHFM29536

I do not think the script is appropriate for including with this PR. 
From a casual read it seems like it could be better if it took user input for a bunch of the variables rater than having to edit the script for every change. I also see it would be easy to add functionality to create an issue automatically via the github API.

**Comment by modem7** [comment]
Agreed, 

If it can be done automagically via variables in github, it certainly should be.

**Comment by adamus1red** [comment]
> 
> 
> Agreed,
> 
> If it can be done automagically via variables in github, it certainly should be.

Made some changes to your script so it'll auto-create the maintainance issue. 

https://gist.github.com/adamus1red/4d80e0ca4a72eb9e2ad053723f7d8581#file-maintainance-sh

**Comment by modem7** [comment]
I think we should be able to use https://github.com/imjohnbo/extract-issue-template-fields to accomplish this somehow

**Comment by q805** [comment]
可以拉取請求合併嗎謝謝

**Comment by Andre601** [comment]
I wonder if this would work slightly better when using issue forms...

Could allow a general structure, tho idk...

**Pull request merged**
