### PR TITLE
Update client.f812e05e.js

### PR DESCRIPTION
**Pull request by v4lerio**
this hot-fix solves:

- resolves upptime/upptime/issues/347 
- resolves upptime/upptime/issues/346

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
Can you tell me more about what you've chnaged?

**Review by flolep2607 — APPROVED** [review]

**Comment by v4lerio** [comment]
@AnandChowdhary the bit that broke the UI was one of  `e.parentNode.deleteNode(e)` 

Unfortunately, as the file is minified I cannot mention the specific line as it is one. Anyway, there are two occurrences, I changed the second one into `e.parentNode&&e.parentNode.removeChild(e)`

Not an elegant solution, only a quick fix. This should be solved the client code not the minified bundle.

**Comment by asm0dey** [comment]
It's kinda funny but it helped me. But of course it's not real fix because it will be overwritten with next codegen. I hope author will find the root cause

**Comment by mrz1836** [comment]
Hi y'all! Can we either merge this fix or find the right solution? Seems there is still an issue related to this: #418

**Review by Edunzz — APPROVED** [review]

**Comment by AnandChowdhary** [comment]
Awesome that this PR was made, but if you can tell me which part of the code you changed, I can guide you on how to update the source file directly instead of updating the generated dist file.

**Review by Vladisvob — APPROVED** [review]

**Comment by AnandChowdhary** [comment]
@v4lerio, did you have a chance to look at my comment? Thanks! :)

**Pull request closed without merging**
