### PR TITLE
👷 Renovate: Update peaceiris/actions-gh-pages action to v4

### PR DESCRIPTION
**Pull request by thomasmerz**
Taken from [my repo's Renovate PR](https://github.com/thomasmerz/upptime/pull/2654).

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
Thanks! No breaking changes we need to be aware of, right?

**Comment by thomasmerz** [comment]
I let all [GH actions run on my PR-branch](https://github.com/thomasmerz/fork-upptime/actions) and all ran fine 👍🏼 

image

**Comment by thomasmerz** [comment]
Ups, letting setup-CI run will change this back - so I had to revert this and force-push.
```
+      - uses: peaceiris/actions-gh-pages@v3.7.3
-      - uses: peaceiris/actions-gh-pages@v4
```

**Comment by AnandChowdhary** [comment]
Thanks! Can you please make the PR here and I'll merge it? https://github.com/upptime/uptime-monitor/blob/2735e1b2bb69e63b987844dd8db29a0315e66b33/src/helpers/workflows.ts#L172

**Comment by thomasmerz** [comment]
Here we go 👍🏼 https://github.com/upptime/uptime-monitor/pull/252

**Pull request closed without merging**
